<a href="https://colab.research.google.com/github/s1230038/googleColaboScrapbook/blob/master/numpy_axis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import numpy as np
import itertools

a = np.array([
            [[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]],
            [[12, 13, 14, 15], [16, 17, 18, 19], [20, 21, 22, 23]]
            ])
print(a)
print('shape = {0}'.format(a.shape) )
for ax0, ax1, ax2 in itertools.product(range(2), range(3), range(4)):
  print("a[%d][%d][%d] = %d" %(ax0 ,ax1 ,ax2 ,a[ax0][ax1][ax2]) )

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
shape = (2, 3, 4)
a[0][0][0] = 0
a[0][0][1] = 1
a[0][0][2] = 2
a[0][0][3] = 3
a[0][1][0] = 4
a[0][1][1] = 5
a[0][1][2] = 6
a[0][1][3] = 7
a[0][2][0] = 8
a[0][2][1] = 9
a[0][2][2] = 10
a[0][2][3] = 11
a[1][0][0] = 12
a[1][0][1] = 13
a[1][0][2] = 14
a[1][0][3] = 15
a[1][1][0] = 16
a[1][1][1] = 17
a[1][1][2] = 18
a[1][1][3] = 19
a[1][2][0] = 20
a[1][2][1] = 21
a[1][2][2] = 22
a[1][2][3] = 23


In [37]:
print("axis = 0")
print(a.sum(axis=0))
print("axis = 1")
print(a.sum(axis=1))
print("axis = 2")
print(a.sum(axis=2))

# print(a.sum(axis=3))  # It will happen to be error

axis = 0
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
axis = 1
[[12 15 18 21]
 [48 51 54 57]]
axis = 2
[[ 6 22 38]
 [54 70 86]]
