<a href="https://colab.research.google.com/github/s1230038/googleColaboScrapbook/blob/master/numpy_axis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import numpy as np
import itertools

a = np.array([
            [[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]],
            [[12, 13, 14, 15], [16, 17, 18, 19], [20, 21, 22, 23]]
            ])
print(a)
print('shape = {0}'.format(a.shape) )
for ax0, ax1, ax2 in itertools.product(range(2), range(3), range(4)):
  print("a[%d][%d][%d] = %d" %(ax0 ,ax1 ,ax2 ,a[ax0][ax1][ax2]) )

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
shape = (2, 3, 4)
a[0][0][0] = 0
a[0][0][1] = 1
a[0][0][2] = 2
a[0][0][3] = 3
a[0][1][0] = 4
a[0][1][1] = 5
a[0][1][2] = 6
a[0][1][3] = 7
a[0][2][0] = 8
a[0][2][1] = 9
a[0][2][2] = 10
a[0][2][3] = 11
a[1][0][0] = 12
a[1][0][1] = 13
a[1][0][2] = 14
a[1][0][3] = 15
a[1][1][0] = 16
a[1][1][1] = 17
a[1][1][2] = 18
a[1][1][3] = 19
a[1][2][0] = 20
a[1][2][1] = 21
a[1][2][2] = 22
a[1][2][3] = 23


The *a.sum(axis=0)* are calculated as below.

|      |  n=0  | n=1 | SUM |
| ---- | ---- | ---- | ---- |
| [n][0][0]| 0| 12| **12** |
| [n][0][1]| 1| 13| **14** |
| [n][0][2]| 2| 14| **16** |
| [n][0][3]| 3| 15| **18** |
| [n][1][0]| 4| 16| **20** |
| [n][1][1]| 5| 17| **22** |
| [n][1][2]| 6| 18| **24** |
| [n][1][3]| 7| 19| **26** |
| [n][2][0]| 8| 20| **28** |
| [n][2][1]| 9| 21| **30** |
| [n][2][2]| 10| 22| **32** |
| [n][2][3]| 11| 23| **34** |



In [38]:
print("axis = 0")
print(a.sum(axis=0))

axis = 0
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


The *a.sum(axis=1)* are calculated as below.

|      |  n=0  | n=1 |  n=2 |SUM |
| ---- | ---- | ---- | ---- | ---- |
| [0][n][0] | 0 | 4 | 8 | **12** |
| [0][n][1] | 1 | 5 | 9 | **15** |
| [0][n][2] | 2 | 6 | 10 | **18** |
| [0][n][3] | 3 | 7 | 11 | **21** |
| [1][n][0] | 12 | 16 | 20 | **48** |
| [1][n][1] | 13 | 17 | 21 | **51** |
| [1][n][2] | 14 | 18 | 22 | **54** |
| [1][n][3] | 15 | 19 | 23 | **57** |

In [39]:
print("axis = 1")
print(a.sum(axis=1))


axis = 1
[[12 15 18 21]
 [48 51 54 57]]


The *a.sum(axis=2)* are calculated as below.

|      |  n=0  | n=1 |  n=2 | n=3 |SUM |
| ---- | ---- | ---- | ---- | ---- | ---- |
| [0][0][n] | 0 | 1 | 2 | 3 | **6** |
| [0][1][n] | 4 | 5 | 6 | 7 | **22** |
| [0][2][n] | 8 | 9 | 10 | 11 | **38** |
| [1][0][n] | 12 | 13 | 14 | 15 | **54** |
| [1][1][n] | 16 | 17 | 18 | 19 | **70** |
| [1][2][n] | 20 | 21 | 22 | 23 | **86** |

In [40]:
print("axis = 2")
print(a.sum(axis=2))


axis = 2
[[ 6 22 38]
 [54 70 86]]


In [0]:
# print(a.sum(axis=3))  # It will happen to be error